version: '3'

services:
  database:
    image: 'postgres'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  movie-app:
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    expose:
      - ${APP_PORT}